# Generated by Django 3.0.4 on 2020-03-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gipi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='history',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
